#!/bin/bash

function usage() {
    echo "USAGE: fk-git-promote <options>"
    echo -e "\nOPTIONS:"
	echo -e "\t-e <env>\n\t\tEnvironment (nm/stage/qa/eng/stagech/cidqa); required"
	echo -e "\t-n \n\t\tBuild, don't deploy; optional"
        echo -e "\t-l \n\t\tBuild, no push ; optional"
	echo -e "\t-N \n\t\tDon't trigger build; optional"
	echo -e "\t-p <pkg> \n\t\tThe package to promote; optional, promotes all packages by default"
    echo -e "\t-b <branch> \n\t\tThe remote branch to promote; optional, promotes master by default"
	echo -e "\t-r <repo> \n\t\tThe remote to promote; optional, promotes origin by default"
    exit 1
}

function die() {
    echo "ERROR: $1" >&2
    echo "Aborting." >&2
    exit 1
}

while getopts "lnNe:p:b:r:" option; do
    case "$option" in
        n) nodeploy=nodeploy;;
        N) nobuild=nobuild;;
	    l) nopush=nopush;;
        e) env="$OPTARG";;
        p) pkg="$OPTARG";;
        b) branch="$OPTARG";;
        r) remote="$OPTARG";;

        [?]) usage;;
    esac
done


# Environment and Package are required attributes
[ -n "$env" ] || usage;

#lock down allowed enviroments
case "$env" in
        local) levn=local;;
        stage) levn=local;;
        stagech) levn=stagech;;
		cidqa) levn=qa;;
esac
[ -z "$levn" ] && die "Promote Not Allowed for $env. Create Pull Request on github.com"

# If package name does not begin with fk-, add it automatically
if [ -n "$pkg" ]; then
	if [ ${pkg#fk-} == ${pkg} ]; then
		pkg="fk-$pkg"
	fi
	pkg="$pkg/"
fi

version=$env-$(date +%Y%m%d-%H%M%S)
if [ ! -z "$nodeploy" ]; then
    version=$version-nodeploy
fi
if [ ! -z "$nobuild" ]; then
    version=$version-nobuild
fi
if [ ! -z "$nopush"]; then 
    version=$version-nopush
fi

[ -z "$branch" ] && branch=master
[ -z "$remote" ] && remote=origin


echo -e "Environment: \033[1;31m$env \033[0m"
echo -e "Package: \033[1;31m${pkg%/} \033[0m"
echo -e "Remote: \033[1;31m$remote \033[0m"
echo -e "Branch: \033[1;31m$branch \033[0m"
echo -e "Tag: \033[1;31m$version \033[0m"
echo
echo -n "Proceed? (y/N): "
read proceed

if [ "$proceed" != "y" ]; then
    echo "OK, not proceeding."
    exit 3
fi

(set -x;
git tag -m "Promoting to $env." release/$pkg$version $remote/${branch} && git push $remote --tags;
)
